### ISSUE TITLE
Runtime Error: Client and Server

### ISSUE THREAD

**Issue by pdr0663** [Lanfei/websocket-lib#1]
I have installed websocket-lib on both my Ubuntu laptop and Raspberry-Pi. I've copied the code from the samples, and I get the following error when trying to connect:

paul@paul-Vostro1310:~/js$ nodejs xbox.js
Server: client connected

/home/paul/node_modules/websocket-lib/lib/frame.js:215
    if (!buffer || !buffer.length || this.isPaused()) {
                                          ^
TypeError: Object #<Receiver> has no method 'isPaused'
    at Receiver._parse (/home/paul/node_modules/websocket-lib/lib/frame.js:215:40)
    at Receiver._write (/home/paul/node_modules/websocket-lib/lib/frame.js:208:7)
    at doWrite (_stream_writable.js:223:10)
    at writeOrBuffer (_stream_writable.js:213:5)
    at Receiver.Writable.write (_stream_writable.js:180:11)
    at write (_stream_readable.js:583:24)
    at flow (_stream_readable.js:592:7)
    at Socket.pipeOnReadable (_stream_readable.js:624:5)
    at Socket.EventEmitter.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:408:10)

Regards,

Paul

**Comment by Lanfei** [comment]
It seems that your node version is too old.

You may download the latest version for Raspberry-Pi(**ARMv6**) [here](https://nodejs.org/en/download/), instead of running:

``` bash
apt-get install nodejs
```

**Comment by pdr0663** [comment]
On the Pi: v0.19.29 says latest version
On Ubuntu laptop: v0.10.25 also says latest version

**Comment by pdr0663** [comment]
Ok, all solved. I'm a NOOB and I was trying to pass an object. Worked when I used JSON.stringify before sending.

Thanks, fun tool!

Issue closed for me.

**Comment by Lanfei** [comment]
You're welcome. ʅ(‾◡◝)
